### ISSUE TITLE
Compilation error when including PSRDADA

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/AMBER#10]
Getting a `dada_hdu_t does not name a type` error when including PSRDADA.
Fixed by adding someting like this to `CommandLine.hpp`:
```
#ifdef HAVE_PSRDADA
    #include <dada_hdu.h>
#endif // HAVE_PSRDADA
```

**Comment by isazi** [comment]
I noticed this in the morning too :)
Fixed in the dada_bug branch, that I will merge back to master when we have working PSRDADA.
