### ISSUE TITLE
Clearer error on wrong device name

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/AMBER#11]
If a device name that does not exist in the config files is specified on the command line, the error is not very clear (`std:out_of_range`). Would it be possible to change it so it is clear from the error that a device with the given name was not found in the config?

**Comment by isazi** [comment]
Sure, I will fix this next week.

**Comment by isazi** [comment]
I believe to have fixed the issue, I will test the development branch to be sure the fix works.

**Comment by isazi** [comment]
Tested on the development branch, it now says that there is no "whatever" specified for device X if you use a device that is not in the configuration file.
