### ISSUE TITLE
-DHAVE_PSRDADA missing from Makefile

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/AMBER#2]
The following is missing from the Makefile:
```
ifdef PSRDADA
        CFLAGS += -DHAVE_PSRDADA
endif
```
Without it, TransientSearch won't compile as it still tries to compile PSRDADA code.

**Comment by jiskattema** [comment]
Thanks, i will add it here. Note that i'm refactoring building the pipeline; there can be a few more spots i've missed.

**Comment by jiskattema** [comment]
Build is fixed in 9a026d7 with and without PSRDADA. Not actually tested.
