### ISSUE TITLE
sampling_rate -> sampling_time

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/AMBER#4]
Request to change the name of the `sampling_rate` parameter to `sampling_time`, as the latter is what actually needs to be put in.

**Comment by isazi** [comment]
Done. I just pushed the change in the output branch. Internally I am still using the sampling rate, but I will change it soon. The change will require a switch to the "output" branch of the AstroData package.

**Comment by isazi** [comment]
AstroData has been updated, now there are no references anymore to sampling rate, it is all sampling time internally and externally.
