### ISSUE TITLE
Compact integration steps like compact dms

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/AMBER#7]
Feature request to also compact over integration steps instead of only over dms when -compact_results is specified. If a pulse is detected at multiple integration steps, only the one with the highest S/N needs to be saved.

**Comment by isazi** [comment]
I am at a conference this week, I will implement this either Friday or next week. It does not sound complex so it should be a matter of few hours.

**Comment by isazi** [comment]
Hi @loostrum I implemented a new compact mode that compacts over DMs and integration steps. It is in the "compact" branch. I tested it with the simple scripts I use and it seems to work, can you test it on your data and see if it works for real?

**Comment by loostrum** [comment]
Thanks @isazi. It works as expected. Could you add a column to the output, similar to compactedDMs, showing in how many integration steps a candidate was found? 
One thing to think about is that the measured arrival time may be slightly different for different integration steps, even though it's all the same candidate. We'll think about that a bit and open a new issue if needed (e.g. add a small time windows in which candidates may be compacted).

**Comment by isazi** [comment]
OK, I will add the new column and let you know when I am done.

**Comment by isazi** [comment]
Done, let me know if everything works as expected.

**Comment by loostrum** [comment]
It does, closing the issue.
