### ISSUE TITLE
PSRDADA header changes

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/AMBER#8]
I'm testing `TransientSearch` + ringbuffer now on ARTS0. Turns out that sampling_time is not set: `TransientSearch` itself doesn't set it and neither does `readPSRDADAHeader` in `AstroData`. Could you add it to the header keys to be read? Preferred name for the key is `TSAMP`, as we use that already.
I also request changing NCHANNELS to NCHAN, as the latter is required when using e.g. `dada_dbdisk` for writing raw data to disk - that way we don't have to put the same parameter twice in the header.

**Comment by isazi** [comment]
Just changed CHANNELS to NCHANS and added TSAMP to the header reader. The code is not here but in AstroData, so you need to pull and compile that one to test the changes.
Also this is just the reader, so someone needs to update the writer too.
Let me know.

**Comment by loostrum** [comment]
Could you make it NCHAN (i.e without the S)? Rest seems ok, thanks.

**Comment by isazi** [comment]
Done.

**Comment by loostrum** [comment]
Thanks!
